### ISSUE TITLE
Cannot read from in-port

### ISSUE THREAD

**Issue by asukiaaa** [mordae/racket-libserialport#2]
Thanks for sharing useful functions.
I succeeded in writing value to Arduino through out-port but I can't read value from in-port.

I tried to read value with using `read-bytes-avail!*` like this.
```racket
(require libserialport)

(define ports (serial-ports))
(define buffer-size 20000)
(define read-buffer (make-bytes buffer-size))

(unless (empty? ports)
  (let ([port-name (list-ref ports 0)])
    (define-values (in out) (open-serial-port port-name))
    (define read-result (read-bytes-avail!* read-buffer in)
    ..
    ))
```

I got the following error occurred on `read-bytes-avail*`.
```
error reading from stream port
  port: 'ttyUSB0
  system error: Bad file descriptor; errno=9
```

Is there any example or way to read data from in-port?

My environment:

Name | Version
--- | ---
OS | ubuntu17.10
Racket | 6.12

Thank you.

**Comment by mordae** [comment]
Thanks for your pull request #3.
Since I am no longer actively using Racket, I have taken the liberty of inviting you to the project.

**Comment by asukiaaa** [comment]
Thank you for merging and giving me authentication of this repository.
I will maintain this.
