### ISSUE TITLE
Bug with Racket CS

### ISSUE THREAD

**Issue by rferrante** [mordae/racket-libserialport#4]
libserialport does not work with Racket v8.0 and above (Racket CS). According to the Racket project:  [it] "intentionally doesn't support scheme_make_fd_output_port."

Here is the error message from Racket:

ffi-obj: could not find export from foreign library
  name: scheme_make_fd_output_port
  library: [all opened]
  system error: dlsym(0x7febccd044c0, scheme_make_fd_output_port): symbol not found
  context...:
   /Applications/Racket v8.1/collects/ffi/unsafe.rkt:255:20
   /Applications/Racket v8.1/collects/ffi/unsafe.rkt:249:2: get-ffi-obj*
   body of "/Users/rferrante/Library/Racket/8.1/pkgs/libserialport/libserialport/private/ffi.rkt"

This was using Racket 8.1 on Mac OS 11.4

**Comment by asukiaaa** [comment]
I cannot help you because I don't have mac pc.
I'm happy if you solve the problem and create a pull request to update codes.

**Comment by asukiaaa** [comment]
@rferrante 
Can you try this code?
https://github.com/mordae/racket-libserialport/pull/5

**Comment by sorawee** [comment]
Note that it's not enough to only test that the module can be loaded (I'm very certain that it will). You should actually use `open-serial-port` and confirm that it works correctly. It should also be tested on other platforms to make sure that the change doesn't break existing code, and this is where @asukiaaa might be able to help.

**Comment by rferrante** [comment]
Thanks, I will try it today and report. My program does use open-serial-port.
